const INPUT = 'input'
const DIV = 'DIV'
const P = 'P'
const BUTTON = 'button'
const IMG = 'IMG'
const ID = 'id'
const SRC = 'src'
const TWO_INDEX = 2
const TWENTY_EIGHT = 28
const AUTOCOMPLETELIST = 'autocomplete-list'
const AUTOCOMPLETEACTIVE = 'autocomplete-active'
const CLASS = 'class'
const AUTOCOMPLETEITEMS = 'autocomplete-items'
const STRONGSTART = '<strong>'
const STRONGEND = '</strong>'
const INPUTHIDDENSTART = '<input type="hidden" value="'
const INPUTHIDDENEND = '<input type="hidden" value="'
const TYPE = 'type'
const CLICK = 'click'
const ZERO_INDEX = 0
const ONE_INDEX = 1
const KEYDOWN = 'keydown'
const KEYUP = 'keyup'
const FORTY = 40
const THIRTYEIGHT = 38
const THIRTEEN = 13
const MINONE = -1
const BUTTONBEER = 'btn btn-primary btn-sm searchForBeer'
const SINGLEBORDERROW = 'row single-div border border'
const COLBEERNAME = 'col-2 beerName'
const BEERNAMEPARAGRAPH = 'beerNameParagraph'
const BEERABV = 'col-1 beerABV'
const BEERABVPARAGRAPH = 'beerABVParagraph'
const BEERTITLE = 'col-3 beerTitle'
const IMGCLASS = 'imgClass'
const BEERDESCRIPTION = 'col-5 beerDescription'
const BEERDESCRIPTIONPARAGRAPH = 'beerDescriptionParagraph'
const FAFASEARCH = 'fa fa-search'
const VALUE = 'value'
const CONTAINERBEER = '.containerBeer'
const WIDTH = 'width'
const HEIGHT = 'height'
const TH70 = '70px'
const BEERADDTOFAVORITES = 'col-1 beerAddToFavorites'
const BEERADDTOFAVORITESBEER = 'btn btn-primary beerAddToFavoritesButton'
const ADD = 'Add'
const MARGINSLEFTRIGHT = '25px 50px'
const BEERNAMEINPUT = 'beerNameInput'
const APIFORBEERNAME = 'https://api.punkapi.com/v2/beers?beer_name='
const PAGINATIONBEER1 = 'https://api.punkapi.com/v2/beers?page='
const PAGINATIONBEER2 = '&beer_name='
const SUCCSESSFULSEARCHES = 'SuccsessArray'
const BODY = 'body'
const DIVFLEXCENTER = 'd-flex justify-content-center'
const BUTTONSUCCESS = 'btn btn-success'
const CLASSBUTTONSUCCESS = '.btn-success'
const LOADMORESTRING = 'Load More Bears'
const BLOCK = 'block'
const NONE = 'none'
const GOTOTOPCLASS = 'goToTop'
const GOTOTOPID = '#goToTopid'

const ROWCLASSNAME = 'row single-div border errorMessage'
const STYLE = 'style'
const ROWSTYLE = 'background-color: red;'
const ERRORMESSAGE = 'There were no properties found for the given location.'
const ERRORMESSAGESTYLE = 'margin: 0px 30px; background-color: red;'
const SEARCHBUTTON = '.searchForBeer'
const TRUE = true
const FALSE = false
const ERRORMESSAGESTRING = '.errorMessage'


const ROWCLASSNAMEWARNING = 'row single-div border warningMessage'
const ROWSTYLEWARNING = 'background-color: yellow; margin-top: 25px;'
const WARNINGMESSAGE = 'No more pages avalible'
const WARNINGMESSAGESTYLE = 'padding-left:40%;margin: 0px 30px; background-color: yellow;'
const WARNINGMESSAGESTRING = '.warningMessage'